language: php
php:
  - '5.5'
  - '5.6'

# Commands to be run before your environment runs.
before_script:
  - composer self-update

script:
  #- phpunit --configure tests/phpunit.yml
  - phpunit --filter testPushAndPop test/UrlTest.php
